- title: true
- text: Intelligent Semver-based hierarchy processing
- shields:
    style: 'flat-square'
    shields:
      - alt: 'Travis'
        image: 'travis/thebruce/semverist/master.svg'
        link: 'https://travis-ci.org/thebruce/semverist'
      - alt: coveralls
        image: 'coveralls/thebruce/semverist.svg'
        link: 'https://coveralls.io/github/thebruce/semverist?branch=master'

- text: The Semverist provides a uniform interface for understanding and manipulating directories, config, and objects with a semver based hierarchy.
- text: Read our full API docs at [https://thebruce.github.io/semverist/](https://thebruce.github.io/semverist/)
- include: './docs/intro.md'
- license: true
- contributors: true