- title: true
- text: Intelligent Semver-based hierarchy processing
- shields:
    style: 'flat-square'
    shields:
      - alt: Build Status
        image: 'https://travis-ci.org/thebruce/semverist.svg?branch=master'
        link: 'https://travis-ci.org/thebruce/semverist'
      - alt: Coverage Status
        image: 'https://coveralls.io/repos/github/thebruce/semverist/badge.svg?branch=master'
        link: 'https://coveralls.io/github/thebruce/semverist?branch=master'
      - alt: Semantic Release
        image: 'https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg'
        link: 'https://github.com/semantic-release/semantic-release'
- text: The Semverist provides a uniform interface for understanding and manipulating directories, config, and objects with a semver based hierarchy.
- include: './docs/intro.md'
- text: API
- jsdoc: lib/configLoader.js
- jsdoc: lib/supers/semverist.js
- license: true
- contributors: true